// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Login your account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login response",
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginResponse"
                        }
                    }
                }
            }
        },
        "/invoice": {
            "get": {
                "description": "Get invoice",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invoice"
                ],
                "summary": "Get invoice",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Invoice response",
                        "schema": {
                            "$ref": "#/definitions/controllers.InvoiceListResponse"
                        }
                    }
                }
            }
        },
        "/invoice/{id}": {
            "get": {
                "description": "Get invoice by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invoice"
                ],
                "summary": "Get invoice by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Invoice id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Invoice response",
                        "schema": {
                            "$ref": "#/definitions/controllers.InvoiceResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update invoice",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invoice"
                ],
                "summary": "Update invoice",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Invoice id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Invoice data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateInvoiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Invoice response",
                        "schema": {
                            "$ref": "#/definitions/controllers.InvoiceResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete invoice",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invoice"
                ],
                "summary": "Delete invoice",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Invoice id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Invoice response",
                        "schema": {
                            "$ref": "#/definitions/controllers.InvoiceResponse"
                        }
                    }
                }
            }
        },
        "/medical-report": {
            "get": {
                "description": "Get medical report",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medical report"
                ],
                "summary": "Get medical report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Patient",
                        "name": "patient",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Medical report response",
                        "schema": {
                            "$ref": "#/definitions/controllers.MedicalReportListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create medical report",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medical report"
                ],
                "summary": "Create medical report",
                "parameters": [
                    {
                        "description": "Medical report data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MedicalReportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Medical report response",
                        "schema": {
                            "$ref": "#/definitions/controllers.MedicalReportResponse"
                        }
                    }
                }
            }
        },
        "/medical-report/{id}": {
            "get": {
                "description": "Get medical report by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medical report"
                ],
                "summary": "Get medical report by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Medical report response",
                        "schema": {
                            "$ref": "#/definitions/controllers.MedicalReportResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update medical report",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medical report"
                ],
                "summary": "Update medical report",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Medical report id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Medical report data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateMedicalReportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Medical report response",
                        "schema": {
                            "$ref": "#/definitions/controllers.MedicalReportResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete medical report",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medical report"
                ],
                "summary": "Delete medical report",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Medical report id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Medical report response",
                        "schema": {
                            "$ref": "#/definitions/controllers.MedicalReportResponse"
                        }
                    }
                }
            }
        },
        "/medicine": {
            "get": {
                "description": "Get medicine",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medicine"
                ],
                "summary": "Get medicine",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Medicine id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Medicine name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Medicine response",
                        "schema": {
                            "$ref": "#/definitions/controllers.MedicineListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create medicine",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medicine"
                ],
                "summary": "Create medicine",
                "parameters": [
                    {
                        "description": "Medicine data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MedicineRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Medicine response",
                        "schema": {
                            "$ref": "#/definitions/controllers.MedicineResponse"
                        }
                    }
                }
            }
        },
        "/medicine/enums": {
            "get": {
                "description": "Get medicine enums",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medicine"
                ],
                "summary": "Get medicine enums",
                "responses": {}
            }
        },
        "/medicine/{id}": {
            "get": {
                "description": "Get medicine by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medicine"
                ],
                "summary": "Get medicine by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Medicine id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Medicine response",
                        "schema": {
                            "$ref": "#/definitions/controllers.MedicineResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update medicine",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medicine"
                ],
                "summary": "Update medicine",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Medicine id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Medicine data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateMedicineRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Medicine response",
                        "schema": {
                            "$ref": "#/definitions/controllers.MedicineResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete medicine",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medicine"
                ],
                "summary": "Delete medicine",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Medicine id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Medicine response",
                        "schema": {
                            "$ref": "#/definitions/controllers.MedicineResponse"
                        }
                    }
                }
            }
        },
        "/patient": {
            "get": {
                "description": "Get patient",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "patient"
                ],
                "summary": "Get patient",
                "responses": {
                    "200": {
                        "description": "Patient response",
                        "schema": {
                            "$ref": "#/definitions/controllers.PatientListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create patient",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "patient"
                ],
                "summary": "Create patient",
                "parameters": [
                    {
                        "description": "Patient data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.PatientRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Patient response",
                        "schema": {
                            "$ref": "#/definitions/controllers.PatientResponse"
                        }
                    }
                }
            }
        },
        "/patient/{id}": {
            "get": {
                "description": "Get patient by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "patient"
                ],
                "summary": "Get patient by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Patient id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Patient response",
                        "schema": {
                            "$ref": "#/definitions/controllers.PatientResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update patient",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "patient"
                ],
                "summary": "Update patient",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Patient id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Patient data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdatePatientRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Patient response",
                        "schema": {
                            "$ref": "#/definitions/controllers.PatientResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete patient",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "patient"
                ],
                "summary": "Delete patient",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Patient id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Patient response",
                        "schema": {
                            "$ref": "#/definitions/controllers.PatientResponse"
                        }
                    }
                }
            }
        },
        "/regulation": {
            "get": {
                "description": "Get regulation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "regulation"
                ],
                "summary": "Get regulation",
                "responses": {
                    "200": {
                        "description": "Regulation response",
                        "schema": {
                            "$ref": "#/definitions/controllers.RegulationListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create regulation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "regulation"
                ],
                "summary": "Create regulation",
                "parameters": [
                    {
                        "description": "Regulation data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.RegulationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Regulation response",
                        "schema": {
                            "$ref": "#/definitions/controllers.RegulationResponse"
                        }
                    }
                }
            }
        },
        "/regulation/{id}": {
            "put": {
                "description": "Update regulation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "regulation"
                ],
                "summary": "Update regulation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Regulation id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Regulation data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateRegulationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Regulation response",
                        "schema": {
                            "$ref": "#/definitions/controllers.RegulationResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete regulation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "regulation"
                ],
                "summary": "Delete regulation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Regulation id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Regulation response",
                        "schema": {
                            "$ref": "#/definitions/controllers.RegulationResponse"
                        }
                    }
                }
            }
        },
        "/staff": {
            "get": {
                "description": "Get staff",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Get staff",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Staff name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Staff response",
                        "schema": {
                            "$ref": "#/definitions/controllers.StaffListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create staff",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Create staff",
                "parameters": [
                    {
                        "description": "Staff data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.StaffRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Staff response",
                        "schema": {
                            "$ref": "#/definitions/controllers.StaffResponse"
                        }
                    }
                }
            }
        },
        "/staff/enums": {
            "get": {
                "description": "Get staff enums",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Get staff enums",
                "responses": {}
            }
        },
        "/staff/{id}": {
            "get": {
                "description": "Get staff by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Get staff by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Staff id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Staff response",
                        "schema": {
                            "$ref": "#/definitions/controllers.StaffResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update staff",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Update staff",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Staff id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Staff data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateStaffRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Staff response",
                        "schema": {
                            "$ref": "#/definitions/controllers.StaffResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete staff",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Delete staff",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Staff id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Staff response",
                        "schema": {
                            "$ref": "#/definitions/controllers.StaffResponse"
                        }
                    }
                }
            }
        },
        "/ticket": {
            "get": {
                "description": "Get ticket",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "Get ticket",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ticket response",
                        "schema": {
                            "$ref": "#/definitions/controllers.TicketListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create waiting ticket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "Create waiting ticket",
                "parameters": [
                    {
                        "description": "Waiting ticket data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.TicketRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Waiting ticket response",
                        "schema": {
                            "$ref": "#/definitions/controllers.TicketListResponse"
                        }
                    }
                }
            }
        },
        "/ticket/enums": {
            "get": {
                "description": "Get ticket enums",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "Get ticket enums",
                "responses": {}
            }
        },
        "/ticket/{id}": {
            "delete": {
                "description": "Delete ticket",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "Delete ticket",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ticket id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ticket response",
                        "schema": {
                            "$ref": "#/definitions/controllers.TicketResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.InvoiceListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Invoice"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.InvoiceResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.Invoice"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "controllers.LoginResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.User"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.MedicalReportListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MedicalReport"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.MedicalReportRequest": {
            "type": "object",
            "required": [
                "doctor_id",
                "patient_id",
                "updated_by"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "diagnose": {
                    "type": "string"
                },
                "doctor_id": {
                    "type": "integer"
                },
                "patient_id": {
                    "type": "integer"
                },
                "prescription": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.PrescriptionRequest"
                    }
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "controllers.MedicalReportResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.MedicalReport"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.MedicineListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Medicine"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.MedicineRequest": {
            "type": "object",
            "required": [
                "id",
                "name",
                "price",
                "quantity",
                "unit",
                "updated_by"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "info": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "unit": {
                    "$ref": "#/definitions/types.MedicineUnit"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "controllers.MedicineResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.Medicine"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.PatientListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Patient"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.PatientRequest": {
            "type": "object",
            "required": [
                "address",
                "birth_date",
                "full_name",
                "gender",
                "identity_card",
                "phone_number",
                "updated_by"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "identity_card": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "controllers.PatientResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.Patient"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.RegulationListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Regulation"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.RegulationRequest": {
            "type": "object",
            "required": [
                "name",
                "updated_by",
                "value"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                },
                "value": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "controllers.RegulationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.Regulation"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.StaffListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Staff"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.StaffRequest": {
            "type": "object",
            "required": [
                "address",
                "birth_date",
                "email",
                "full_name",
                "gender",
                "identity_card",
                "password",
                "phone_number",
                "role",
                "updated_by"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/types.Gender"
                },
                "identity_card": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/types.Role"
                },
                "salary": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/types.StaffStatus"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "controllers.StaffResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.Staff"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.TicketListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Ticket"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.TicketRequest": {
            "type": "object",
            "required": [
                "patient_id",
                "updated_by"
            ],
            "properties": {
                "patient_id": {
                    "type": "integer"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "controllers.TicketResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.Ticket"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.UpdateInvoiceRequest": {
            "type": "object",
            "properties": {
                "delivery_status": {
                    "type": "boolean"
                },
                "payment_status": {
                    "type": "boolean"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "controllers.UpdateMedicalReportRequest": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "diagnose": {
                    "type": "string"
                },
                "doctor_id": {
                    "type": "integer"
                },
                "patient_id": {
                    "type": "integer"
                },
                "prescription": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.PrescriptionRequest"
                    }
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "controllers.UpdateMedicineRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "info": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "unit": {
                    "$ref": "#/definitions/types.MedicineUnit"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "controllers.UpdatePatientRequest": {
            "type": "object",
            "required": [
                "address",
                "birth_date",
                "full_name",
                "gender",
                "identity_card",
                "phone_number"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "identity_card": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "controllers.UpdateRegulationRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                },
                "value": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "controllers.UpdateStaffRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/types.Gender"
                },
                "identity_card": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/types.Role"
                },
                "salary": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/types.StaffStatus"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "controllers.UpdateTicketRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "$ref": "#/definitions/types.TicketStatus"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "models.Invoice": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "delivery_status": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "medical_report": {
                    "$ref": "#/definitions/models.MedicalReport"
                },
                "medical_report_id": {
                    "type": "integer"
                },
                "payment_status": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "models.MedicalReport": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "diagnose": {
                    "type": "string"
                },
                "doctor": {
                    "$ref": "#/definitions/models.Staff"
                },
                "doctor_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "patient_id": {
                    "type": "integer"
                },
                "prescription": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Prescription"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "models.Medicine": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "info": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "unit": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "models.Patient": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "identity_card": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "models.Regulation": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                },
                "value": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "models.Staff": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "identity_card": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "salary": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "models.Ticket": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "number": {
                    "type": "integer"
                },
                "patient": {
                    "$ref": "#/definitions/models.Patient"
                },
                "patient_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "types.Gender": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "Male",
                "Female",
                "Other"
            ]
        },
        "types.MedicineUnit": {
            "type": "integer",
            "enum": [
                1,
                2
            ],
            "x-enum-varnames": [
                "Pill",
                "Bottle"
            ]
        },
        "types.Role": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "Receptionist",
                "Doctor",
                "Pharmacist",
                "Admin"
            ]
        },
        "types.StaffStatus": {
            "type": "integer",
            "enum": [
                1,
                2
            ],
            "x-enum-varnames": [
                "Working",
                "Quit"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "clinicly.fly.dev",
	BasePath:         "/api/v1",
	Schemes:          []string{"https"},
	Title:            "Clinic Management",
	Description:      "Clinic Management API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
