-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS public."NhanVien" CASCADE;

CREATE TABLE IF NOT EXISTS public."NhanVien"
(
    "MaNV" serial,
    "HoTen" character varying(50),
    "NgaySinh" timestamp,
    "GioiTinh" character varying(5),
    "DiaChi" character varying(100),
    "CCCD" character(12),
    "SDT" character(10),
    "Email" character varying(50),
    "LoaiNV" character varying(10),
    "MucLuong" integer,
    "TrangThai" character varying(10),
    "Password" character varying(255),
    "NgayTao" timestamp with time zone NOT NULL DEFAULT NOW(),
	"NgayCapNhat" TIMESTAMP with time zone NOT NULL DEFAULT NOW(),
	"CapNhatBoi" integer,
    PRIMARY KEY ("MaNV")
);

DROP TABLE IF EXISTS public."HoaDon" CASCADE;

CREATE TABLE IF NOT EXISTS public."HoaDon"
(
    "MaHD" serial,
    "TongTien" integer NOT NULL,
    "TTThanhToan" boolean DEFAULT FALSE,
    "TTGiaoThuoc" boolean DEFAULT FALSE,
    "MaPK" integer,
	"NgayTao" timestamp with time zone NOT NULL DEFAULT NOW(),
	"NgayCapNhat" TIMESTAMP with time zone NOT NULL DEFAULT NOW(),
	"CapNhatBoi" integer,
    PRIMARY KEY ("MaHD")
);

DROP TABLE IF EXISTS public."PhieuKham" CASCADE;

CREATE TABLE IF NOT EXISTS public."PhieuKham"
(
    "MaPK" serial,
    "MaBN" integer,
	"BacSi" integer,
    "ChanDoan" text,
    "NgayKham" timestamp with time zone NOT NULL DEFAULT NOW(),
	"NgayTao" timestamp with time zone NOT NULL DEFAULT NOW(),
	"NgayCapNhat" TIMESTAMP with time zone NOT NULL DEFAULT NOW(),
	"CapNhatBoi" integer,
    PRIMARY KEY ("MaPK")
);

DROP TABLE IF EXISTS public."BenhNhan" CASCADE;

CREATE TABLE IF NOT EXISTS public."BenhNhan"
(
    "MaBN" serial,
    "HoTen" character varying(50),
    "GioiTinh" character varying(5),
    "NgaySinh" timestamp,
    "CCCD" character(12),
    "DiaChi" character varying(100),
    "SDT" character(10),
    "NgayTao" timestamp with time zone NOT NULL DEFAULT NOW(),
	"NgayCapNhat" TIMESTAMP with time zone NOT NULL DEFAULT NOW(),
	"CapNhatBoi" integer,
    PRIMARY KEY ("MaBN")
);

DROP TABLE IF EXISTS public."Thuoc" CASCADE;

CREATE TABLE IF NOT EXISTS public."Thuoc"
(
    "MaThuoc" character varying(50),
    "TenThuoc" character varying(50),
    "SoLuong" integer DEFAULT 0,
    "DonGia" integer,
    "ThongTin" text,
    "DonVi" character varying(50),
	"NgayTao" timestamp with time zone NOT NULL DEFAULT NOW(),
	"NgayCapNhat" TIMESTAMP with time zone NOT NULL DEFAULT NOW(),
	"CapNhatBoi" integer,
    PRIMARY KEY ("MaThuoc")
);


DROP TABLE IF EXISTS public."DonThuoc" CASCADE;

CREATE TABLE IF NOT EXISTS public."DonThuoc"
(
    "MaPK" integer,
    "MaThuoc" character varying(50),
    "SoLuong" integer DEFAULT 0,
    "CachDung" text,
	"NgayTao" timestamp with time zone NOT NULL DEFAULT NOW(),
	"NgayCapNhat" TIMESTAMP with time zone NOT NULL DEFAULT NOW(),
	"CapNhatBoi" integer,
    PRIMARY KEY ("MaPK", "MaThuoc")
);


DROP TABLE IF EXISTS public."PhieuDoiKham" CASCADE;

CREATE TABLE IF NOT EXISTS public."PhieuDoiKham"
(
    "MaPDK" serial,
    "MaBN" integer,
    "STT" int2,
    "TrangThai" character varying(50),
    "NgayKham" timestamp with time zone NOT NULL DEFAULT NOW(),
	"NgayTao" timestamp with time zone NOT NULL DEFAULT NOW(),
	"NgayCapNhat" TIMESTAMP with time zone NOT NULL DEFAULT NOW(),
	"CapNhatBoi" integer,
    PRIMARY KEY ("MaPDK")
);

DROP TABLE IF EXISTS public."PhieuNhapThuoc" CASCADE;

CREATE TABLE IF NOT EXISTS public."PhieuNhapThuoc"
(
    "MaPN" serial,
    "MaThuoc" character varying(50),
    "NgayNhap" timestamp with time zone NOT NULL DEFAULT NOW(),
    "SoLuong" integer DEFAULT 0,
	"NgayTao" timestamp with time zone NOT NULL DEFAULT NOW(),
	"NgayCapNhat" TIMESTAMP with time zone NOT NULL DEFAULT NOW(),
	"CapNhatBoi" integer,
    PRIMARY KEY ("MaPN")
);

DROP TABLE IF EXISTS public."QuyDinh" CASCADE;

CREATE TABLE IF NOT EXISTS public."QuyDinh"
(
    "MaQD" character varying(20),
    "TenQD" character varying(50),
    "GiaTri" integer,
    "NgayTao" timestamp with time zone NOT NULL DEFAULT NOW(),
	"NgayCapNhat" TIMESTAMP with time zone NOT NULL DEFAULT NOW(),
	"CapNhatBoi" serial,
    PRIMARY KEY ("MaQD")
);

ALTER TABLE IF EXISTS public."NhanVien"
    ADD CONSTRAINT "FK_NhanVien_NhanVien" FOREIGN KEY ("CapNhatBoi")
    REFERENCES public."NhanVien" ("MaNV") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

ALTER TABLE IF EXISTS public."HoaDon"
    ADD CONSTRAINT "FK_HoaDon_PK" FOREIGN KEY ("MaPK")
    REFERENCES public."PhieuKham" ("MaPK") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."HoaDon"
    ADD CONSTRAINT "FK_HoaDon_NhanVien" FOREIGN KEY ("CapNhatBoi")
    REFERENCES public."NhanVien" ("MaNV") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."BenhNhan"
    ADD CONSTRAINT "FK_BenhNhan_NhanVien" FOREIGN KEY ("CapNhatBoi")
    REFERENCES public."NhanVien" ("MaNV") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."PhieuKham"
    ADD CONSTRAINT "FK_PhieuKham_BacSi" FOREIGN KEY ("BacSi")
    REFERENCES public."NhanVien" ("MaNV") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;
	

ALTER TABLE IF EXISTS public."PhieuKham"
    ADD CONSTRAINT "FK_PhieuKham_NhanVien" FOREIGN KEY ("CapNhatBoi")
    REFERENCES public."NhanVien" ("MaNV") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."PhieuKham"
    ADD CONSTRAINT "FK_PhieuKham_BenhNhan" FOREIGN KEY ("MaBN")
    REFERENCES public."BenhNhan" ("MaBN") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Thuoc"
    ADD CONSTRAINT "FK_Thuoc_NhanVien" FOREIGN KEY ("CapNhatBoi")
    REFERENCES public."NhanVien" ("MaNV") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."DonThuoc"
    ADD CONSTRAINT "FK_DonThuoc_PhieuKham" FOREIGN KEY ("MaPK")
    REFERENCES public."PhieuKham" ("MaPK") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."DonThuoc"
    ADD CONSTRAINT "FK_DonThuoc_Thuoc" FOREIGN KEY ("MaThuoc")
    REFERENCES public."Thuoc" ("MaThuoc") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."DonThuoc"
    ADD CONSTRAINT "FK_DonThuoc_NhanVien" FOREIGN KEY ("CapNhatBoi")
    REFERENCES public."NhanVien" ("MaNV") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."PhieuDoiKham"
    ADD CONSTRAINT "FK_PDK_BenhNhan" FOREIGN KEY ("MaBN")
    REFERENCES public."BenhNhan" ("MaBN") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;



ALTER TABLE IF EXISTS public."PhieuDoiKham"
    ADD CONSTRAINT "FK_PDK_NhanVien" FOREIGN KEY ("CapNhatBoi")
    REFERENCES public."NhanVien" ("MaNV") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."PhieuNhapThuoc"
    ADD CONSTRAINT "FK_PNT_NhanVien" FOREIGN KEY ("CapNhatBoi")
    REFERENCES public."NhanVien" ("MaNV") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."PhieuNhapThuoc"
    ADD CONSTRAINT "FK_PNT_Thuoc" FOREIGN KEY ("MaThuoc")
    REFERENCES public."Thuoc" ("MaThuoc") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."QuyDinh"
    ADD CONSTRAINT "FK_QuyDinh_NhanVien" FOREIGN KEY ("CapNhatBoi")
    REFERENCES public."NhanVien" ("MaNV") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


CREATE OR REPLACE FUNCTION public.update_timestamp()
    RETURNS trigger
    LANGUAGE plpgsql
AS
$function$
BEGIN
    NEW."NgayCapNhat" = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$function$
;

create trigger update_timestamp
    before update
    on public."NhanVien"
    for each row
execute procedure update_timestamp();

create trigger update_timestamp
    before update
    on public."PhieuKham"
    for each row
execute procedure update_timestamp();

create trigger update_timestamp
    before update
    on public."Thuoc"
    for each row
execute procedure update_timestamp();

create trigger update_timestamp
    before update
    on public."QuyDinh"
    for each row
execute procedure update_timestamp();

create trigger update_timestamp
    before update
    on public."BenhNhan"
    for each row
execute procedure update_timestamp();

create trigger update_timestamp
    before update
    on public."HoaDon"
    for each row
execute procedure update_timestamp();

create trigger update_timestamp
    before update
    on public."PhieuNhapThuoc"
    for each row
execute procedure update_timestamp();

create trigger update_timestamp
    before update
    on public."DonThuoc"
    for each row
execute procedure update_timestamp();

create trigger update_timestamp
    before update
    on public."PhieuDoiKham"
    for each row
execute procedure update_timestamp();


CREATE OR REPLACE FUNCTION func_auto_stt() RETURNS trigger AS 
$$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE public."PhieuDoiKham"
    SET "STT" = COALESCE((SELECT "STT" FROM "PhieuDoiKham" 
				 WHERE "NgayTao" >= DATE(NOW())
				 ORDER BY "NgayTao" DESC
				 LIMIT 1), 0) + 1
    WHERE "MaPDK" = NEW."MAPDK";
  END IF;
  RETURN NULL;
END
$$
LANGUAGE PLPGSQL;

END;
